<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>URL _input_publish pop up</name>
   <tag></tag>
   <elementGuidId>5890bdc2-3e62-4da8-bdb6-b560bad38ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.PublishUrl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[49]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PublishUrl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-header-fixed page-sidebar-closed-hide-logo page-content-white flowbody&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;page-content-wrapper&quot;]/div[@class=&quot;popup publish-modal&quot;]/div[@class=&quot;publish-modal-wrapper&quot;]/div[@class=&quot;publish-modal-details-wrap clearfix&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;publish-modal-left col-sm-7&quot;]/div[@class=&quot;publish-modal-url clearfix&quot;]/div[@class=&quot;publish-modal-input publish-modal-input-right&quot;]/input[@class=&quot;PublishUrl&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[49]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div/div/div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
