<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>3ec9822d-8434-4593-bdbe-3113101f94ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='text-block-editable']/div/div[2]/div/div/button[4]/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.addContentBoxButton.ScTooltipBtn > span > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/settings.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preview-screen&quot;)/div[@id=&quot;order_1&quot;]/div[@class=&quot;plain-text-inner col-sm-7 odd-col&quot;]/div[@class=&quot;text-block-top&quot;]/div[@class=&quot;text-block&quot;]/div[@id=&quot;text-block-editable&quot;]/div[@class=&quot;fr-wrapper&quot;]/div[@class=&quot;fr-element fr-view&quot;]/div[@class=&quot;PlainTextContainer clearfix&quot;]/div[@class=&quot;content-box clearfix&quot;]/button[@class=&quot;addContentBoxButton ScTooltipBtn&quot;]/span[1]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='text-block-editable']/div/div[2]/div/div/button[4]/span/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/span/img</value>
   </webElementXpaths>
</WebElementEntity>
