<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vv</name>
   <tag></tag>
   <elementGuidId>e68b20f7-a7df-4bbe-9e04-e5266ff88733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[6]/div[1]/div[1]/div[2]/div[1]/div[5]/div[1]/div[2]/div[3]/ul[1]/li[1]/span[1]/input[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
