<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create user_btn company</name>
   <tag></tag>
   <elementGuidId>e5beaf56-804f-49a5-a8a3-b5ef82622120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.isFloatRight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;companyusers&quot;]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>isFloatRight</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CreateUser('WdI8k1n6lRbPJRlLlCG4zyBSrVPMeTBAqxW60azhbjE=')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create User</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companyusers&quot;)/div[@class=&quot;common_module_view company_user_view&quot;]/div[@class=&quot;view_top clearfix&quot;]/button[@class=&quot;isFloatRight&quot;]</value>
   </webElementProperties>
</WebElementEntity>
